### PR TITLE
Check SOURCE_ID and source_id

### PR DESCRIPTION
**Pull request by tomasstolker**
- The column of the Gaia source ID was changed from source_id to SOURCE_ID so both are now checked
- The `gaia_epoch` attribute needed to be set when reading from a `query_file`
- ~~Fixed an issue related to the number of dimensions when plotting the posterior~~

### CODE REVIEW

**Comment by gotten** [comment]
I get the same error as the CI on a fresh install of your PR.

**Comment by gotten** [comment]
ndim also includes the parameters of the host star. so it is bigger than the amount of labels

**Comment by tomasstolker** [comment]
Right, I agree, it requires a more complete implementation! Let me try to fix this case and I will leave a more robust implementation for someone else, since I don't know the code sufficiently well for that.

**Comment by gotten** [comment]
Still crashes?. So label is defined by us as something that is 4 or 5 long. And cornerplot looks at the size of samples (extracted from dynesty results) for the size of the for loop that also goes over the labels. So there can be a mismatch there.

**Comment by tomasstolker** [comment]
I couldn't find an easy fix, so reverted those changes!

**Pull request merged**
