### PR TITLE
Introduce host star priors, based on 5D+RV Gaia statistics (incl. covariance)

### LINKED ISSUE #35: Handling Gaia DR3 errors for the host star
Considering the Gaia DR3 position, pm, parallax and rv for the host star have errors that become relevant at GRAVITY's accuracy we should implement a way to include the Gaia error into the fit. For instance, HD 131399A has a positional error of 30 microarcsec in RA and DEC. Otherwise the posteriors for the background object do not include the error in the host star.

A way to implement it, is to redraw the host_star location from the DR3 distribution. This is computationally intensive and will at least double the execution time because we will need to setup the catalog and do transform_cat for the host for every new location.

Not sure how to implement it efficiently in combination with a fitter like emcee / dynesty. Give the host star parameters as additional parameters to the model and add the likelihood function for Gaia DR3 ? This would double the amount of parameters that are being optimized which might lengthen the convergence time and further increase the amount of calls needed to the model ? 

Here I can also say that for the purpose of checking if a point source follows a background-like trajectory this is not needed. But it is needed for accurate BG star parameters. Not an immediate priority.

### PR DESCRIPTION
**Pull request by gotten**
Closes #35. 

Potentially could use another diagnostic plot where host star parameters are compared with the prior to make sure it is consistent. 

Might crash if Gaia has no RV datapoint.

### CODE REVIEW

**Comment by gotten** [comment]
Also setting ndim=5 in dynesty is expected to crash on making the plots because of the hardcoded best_pars.

**Comment by gotten** [comment]
Also closes #38 .

**Review by wbalmer — APPROVED** [review]
Looks good to me, I tested for a few use cases on my end. I'll open an issue to update stationtrackplot (I want to update the functionality for that function in general). Is it feasible within this framework to assume a uniform (or perhaps neighborhood) distribution on stellar RVs if the RV information is missing in Gaia? If not, no worries, but if so, I'd like to open an issue to implement that catch, just in case stellar RV isn't available.

**Comment by gotten** [comment]
Yes, I was being lazy by inserting the RV prior into the multivariate PPF. It's an independent measure anyway. We can make it a separate prior that can be overridden (with another normal distr, or uniform distr). This might give a slight performance boost too because the multivariate PPF has less dimensions.

I can separate out the RV prior but I don't know the best way of implementing an override.

**Pull request merged**
